### ISSUE TITLE
Wrong char cyrillic "Ы" U+042B &#1067;

### ISSUE THREAD

**Issue by iMega** [EbenSorkin/Merriweather#29]
Cyrillic Capital Letter Yeru
unicode: `U+042B`
htmlcode: `&#1067;`

Right: Ы

**Comment by EbenSorkin** [comment]
That’s really not good. I’ll have to fix that.

-e.

**Comment by davelab6** [comment]
There are a number of minor things to be done. Maybe by end of this month I will try to see to them.

**Comment by davelab6** [comment]
cc @alexeiva

**Comment by alexeiva** [comment]
has been fixed in PR https://github.com/EbenSorkin/Merriweather/pull/34

**Comment by marianmaximciuc** [comment]
the Cyrillic Capital Letter Yeru is still wrong char
unicode: U+042B
htmlcode: &#1067;

Currently it look like this: IЬ (it's wrong)
Right: Ы

**Comment by davelab6** [comment]
Sorry the delay on pushing the fix to production

On Apr 19, 2017 4:47 AM, "Marian Maximciuc" <notifications@github.com>
wrote:

the Cyrillic Capital Letter Yeru is still wrong char
unicode: U+042B
htmlcode: Ы

Currently it look like this: IЬ (it's wrong)
Right: Ы

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/EbenSorkin/Merriweather/issues/29#issuecomment-295168952>,
or mute the thread

**Comment by marcusatbang** [comment]
Is this going to be fixed?

**Comment by EbenSorkin** [comment]
Yes. It will be.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EbenSorkin** [comment]
The reversion that broke this again is fixed in the new files. Hopefully that goes live quite soon now.

**Comment by davelab6** [comment]
Thanks!

**Comment by iMega** [comment]
Thanks!
